### ISSUE TITLE
Telemetry fails to send when threaded runtime not linked in

### ISSUE THREAD

**Issue by dmvianna** [aesiniath/unbeliever#161]
I wasn't able to send data to *honeycomb*

```bash
export HONEYCOMB_TEAM="<api-key>"
cabal run mycommand -- --telemetry=honeycomb --dataset=mydataset
... 
internal: Reconnecting to Honeycomb
internal: Failed to re-establish connection to Honeycomb
```

Then I tried `--verbose`
```bash
internal: Reconnecting to Honeycomb
internal: Failed to re-establish connection to Honeycomb
02:12:50Z (00.554) Sending telemetry failed (Exception: user error (RTS doesn't support multiple OS threads (use ghc -threaded when linking))); Restarting exporter.
```
Adding `-threaded` to `ghc-options` in `myproject.cabal` fixed the problem.

There are actually two problems here:

1. `Core.Telemetry` fails, there is a helpful error message being generated, but it isn't shown by default. This is bad. I initially assumed that the problem was my environment variables, not `Core.Telemetry`. If it is failing, it should spit a `critical` log and tell me something is not going to work;

2. If there is a required `ghc-option` without which `Core.Telemetry` won't work, it *should not compile*. It should spit the issue as soon as it figures my options are wrong, and save me founding it at runtime.

**Comment by dmvianna** [comment]
Failing all of that, a line in the docs would go a long way too.

**Comment by istathar** [comment]
It's been years since I compiled a Haskell program without the `-threaded` option. It really should just be the default, but it isn't. So, I agree we should test for it.

I've been looking around GHC.\* in **base** and haven't found a way to probe _at runtime_ which runtime is linked in? Anyone know a way?

And I agree, if it isn't there then we should `critical` and bomb out. The rest of the library makes heavy use of STM. I'm a bit surprised that anything else was working without the threaded runtime linked in.

**Comment by istathar** [comment]
@puffnfresh suggested we look at `rtsSupportsBoundThreads` in Control.Concurrent. Looking that up inadvertently led me to System.Posix.Internals which has a `hostIsThreaded` :: Bool. Might do the trick.
